apiVersion: v1
kind: Service
metadata:
  name: api-henrique-svc
spec:
  selector:
    app: web
  ports:
    - name: api-henrique
      port: 4000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-henrique-svc
  labels:
    app: web
    tier: frontend
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  template:
    metadata:
      name: api-henrique-svc
      labels:
        app: web
        tier: frontend
    spec:
      containers:
        - name: api-henrique
          image: hsulimann/prometheus-runner:1.0.0
